FROM quay.io/almalinuxorg/9-minimal:9

RUN microdnf install -y dnf \
    && dnf remove -y microdnf

RUN dnf update -y \
    && dnf install -y --allowerasing @core @base @infiniband @development\
    && dnf install -y --allowerasing \
      dhclient \
      initscripts \
      ipmitool \
      kernel-core \
      kernel-modules \
      net-tools \
      nfs-utils \
      pciutils \
      rsync \
      strace \
      sudo \
      wget \
      words \
    && dnf install -y epel-release elrepo-release \
    && dnf update -y \
    && dnf install -y --allowerasing \
      kmod-mlx4 \
    && dnf remove -y selinux-policy \
    && dnf clean all

RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
