FROM localhost/almalinux-9:latest

RUN dnf install -y epel-release elrepo-release \
    && dnf update -y \
    && dnf install -y --allowerasing \
      @base \
      @infiniband \
      @development \
      shim \
      grub2 \
      csh \
      glibc-langpack-en \
      kmod-mlx4 \
      opensm \
      ipa-client \
      lua-term \
      tcl \
      munge \
      slurm \
      slurm-slurmd \
      slurm-perlapi \
    && dnf clean all

RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the UCO HPC cluster, Buddy 2.5.", \
      "\n", ]
